/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastiq;

import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author kmike
 */
public class TestIQ extends javax.swing.JFrame {

    /**
     * Creates new form TestIQ
     */
    public TestIQ() {
        initComponents();

    }
    int no1;
    int no2;

    public void rdm() {
        Random m = new Random();
        no1 = m.nextInt(10);
        no2 = m.nextInt(10);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        homepane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        gamepanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        subtbutton = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ScoreLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelComputecard = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        additionpanel = new javax.swing.JPanel();
        na1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        na2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfaans = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelresult = new javax.swing.JLabel();
        additionsubmit = new javax.swing.JButton();
        subtractionpanel = new javax.swing.JPanel();
        ns1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ns2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfsans = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelresult1 = new javax.swing.JLabel();
        subdibmit = new javax.swing.JButton();
        multiplicationpanel = new javax.swing.JPanel();
        nm1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nm2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mans = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        labelresult2 = new javax.swing.JLabel();
        mulsubmit = new javax.swing.JButton();
        divisionpanel = new javax.swing.JPanel();
        nd1 = new javax.swing.JLabel();
        nd2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtans = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        labelresult3 = new javax.swing.JLabel();
        divSubmit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(598, 423));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p(evt);
            }
        });
        getContentPane().setLayout(null);

        panelHome.setOpaque(false);
        panelHome.setLayout(new java.awt.CardLayout());

        homepane.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(255, 204, 51));
        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("TEST IQ");

        jButton2.setText("CONTINUE");

        jButton3.setText("PLAY GAME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homepaneLayout = new javax.swing.GroupLayout(homepane);
        homepane.setLayout(homepaneLayout);
        homepaneLayout.setHorizontalGroup(
            homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepaneLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homepaneLayout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButton3)
                .addGap(197, 197, 197))
        );
        homepaneLayout.setVerticalGroup(
            homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepaneLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(homepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(108, 108, 108))
        );

        panelHome.add(homepane, "card2");

        gamepanel.setOpaque(false);
        gamepanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setOpaque(false);

        addButton.setText("Addition");
        addButton.setOpaque(false);
        addButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/fastiq/minion.jpg"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        subtbutton.setText("Subtraction");
        subtbutton.setOpaque(false);
        subtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtbuttonActionPerformed(evt);
            }
        });

        multButton.setText("Multiplication");
        multButton.setOpaque(false);
        multButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multButtonActionPerformed(evt);
            }
        });

        divButton.setText("Division");
        divButton.setOpaque(false);
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        jPanel5.setOpaque(false);

        ScoreLabel.setBackground(new java.awt.Color(255, 255, 102));
        ScoreLabel.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        ScoreLabel.setForeground(new java.awt.Color(0, 0, 153));
        ScoreLabel.setText("0");

        jLabel19.setBackground(new java.awt.Color(255, 255, 102));
        jLabel19.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("SCORES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(ScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(divButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(buttonsPanelLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(subtbutton)
                .addGap(34, 34, 34)
                .addComponent(multButton)
                .addGap(31, 31, 31)
                .addComponent(divButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gamepanel.add(buttonsPanel, java.awt.BorderLayout.LINE_START);

        panelComputecard.setOpaque(false);
        panelComputecard.setLayout(new java.awt.CardLayout());

        jPanel6.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelComputecard.add(jPanel6, "card6");

        additionpanel.setOpaque(false);

        na1.setBackground(new java.awt.Color(255, 255, 102));
        na1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        na1.setForeground(new java.awt.Color(0, 0, 204));

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("compute the value of");

        na2.setBackground(new java.awt.Color(255, 255, 102));
        na2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        na2.setForeground(new java.awt.Color(51, 51, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 102));
        jLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("+");

        tfaans.setBackground(new java.awt.Color(255, 255, 102));
        tfaans.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "my answer is", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        tfaans.setOpaque(false);

        jPanel1.setOpaque(false);

        labelresult.setBackground(new java.awt.Color(255, 255, 102));
        labelresult.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        labelresult.setForeground(new java.awt.Color(0, 0, 153));

        additionsubmit.setText("submit");
        additionsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(additionsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(labelresult, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(additionsubmit)
                    .addComponent(labelresult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout additionpanelLayout = new javax.swing.GroupLayout(additionpanel);
        additionpanel.setLayout(additionpanelLayout);
        additionpanelLayout.setHorizontalGroup(
            additionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionpanelLayout.createSequentialGroup()
                .addGroup(additionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(additionpanelLayout.createSequentialGroup()
                        .addGroup(additionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(additionpanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(additionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfaans, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(additionpanelLayout.createSequentialGroup()
                                        .addComponent(na1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(additionpanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        additionpanelLayout.setVerticalGroup(
            additionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(additionpanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(additionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(na1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tfaans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        panelComputecard.add(additionpanel, "card5");

        subtractionpanel.setOpaque(false);

        ns1.setBackground(new java.awt.Color(255, 255, 102));
        ns1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        ns1.setForeground(new java.awt.Color(0, 0, 204));

        jLabel8.setBackground(new java.awt.Color(255, 255, 102));
        jLabel8.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("compute the value of");

        ns2.setBackground(new java.awt.Color(255, 255, 102));
        ns2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        ns2.setForeground(new java.awt.Color(51, 51, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 102));
        jLabel10.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("-");

        tfsans.setBackground(new java.awt.Color(255, 255, 102));
        tfsans.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "my answer is", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        tfsans.setOpaque(false);

        jPanel2.setOpaque(false);

        labelresult1.setBackground(new java.awt.Color(255, 255, 102));
        labelresult1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        labelresult1.setForeground(new java.awt.Color(0, 0, 153));

        subdibmit.setText("submit");
        subdibmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subdibmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(subdibmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(labelresult1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subdibmit)
                    .addComponent(labelresult1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout subtractionpanelLayout = new javax.swing.GroupLayout(subtractionpanel);
        subtractionpanel.setLayout(subtractionpanelLayout);
        subtractionpanelLayout.setHorizontalGroup(
            subtractionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtractionpanelLayout.createSequentialGroup()
                .addGroup(subtractionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subtractionpanelLayout.createSequentialGroup()
                        .addGroup(subtractionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subtractionpanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(subtractionpanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(subtractionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfsans, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(subtractionpanelLayout.createSequentialGroup()
                                        .addComponent(ns1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addGap(33, 33, 33)
                                        .addComponent(ns2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(subtractionpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        subtractionpanelLayout.setVerticalGroup(
            subtractionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subtractionpanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(subtractionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ns2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ns1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tfsans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelComputecard.add(subtractionpanel, "card5");

        multiplicationpanel.setOpaque(false);

        nm1.setBackground(new java.awt.Color(255, 255, 102));
        nm1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        nm1.setForeground(new java.awt.Color(0, 0, 204));

        jLabel12.setBackground(new java.awt.Color(255, 255, 102));
        jLabel12.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("compute the value of");

        nm2.setBackground(new java.awt.Color(255, 255, 102));
        nm2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        nm2.setForeground(new java.awt.Color(51, 51, 255));

        jLabel14.setBackground(new java.awt.Color(255, 255, 102));
        jLabel14.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("*");

        mans.setBackground(new java.awt.Color(255, 255, 102));
        mans.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "my answer is", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        mans.setOpaque(false);

        jPanel3.setOpaque(false);

        labelresult2.setBackground(new java.awt.Color(255, 255, 102));
        labelresult2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        labelresult2.setForeground(new java.awt.Color(0, 0, 153));

        mulsubmit.setText("submit");
        mulsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(mulsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(labelresult2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mulsubmit)
                    .addComponent(labelresult2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout multiplicationpanelLayout = new javax.swing.GroupLayout(multiplicationpanel);
        multiplicationpanel.setLayout(multiplicationpanelLayout);
        multiplicationpanelLayout.setHorizontalGroup(
            multiplicationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplicationpanelLayout.createSequentialGroup()
                .addGroup(multiplicationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multiplicationpanelLayout.createSequentialGroup()
                        .addGroup(multiplicationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(multiplicationpanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(multiplicationpanelLayout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(multiplicationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mans, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(multiplicationpanelLayout.createSequentialGroup()
                                        .addComponent(nm1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nm2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(multiplicationpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        multiplicationpanelLayout.setVerticalGroup(
            multiplicationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiplicationpanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(multiplicationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nm2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nm1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        panelComputecard.add(multiplicationpanel, "card5");

        divisionpanel.setOpaque(false);

        nd1.setBackground(new java.awt.Color(255, 255, 102));
        nd1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        nd1.setForeground(new java.awt.Color(0, 0, 204));

        nd2.setBackground(new java.awt.Color(255, 255, 102));
        nd2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        nd2.setForeground(new java.awt.Color(51, 51, 255));

        jLabel18.setBackground(new java.awt.Color(255, 255, 102));
        jLabel18.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("/");

        txtans.setBackground(new java.awt.Color(255, 255, 102));
        txtans.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "my answer is", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        txtans.setOpaque(false);

        jPanel4.setOpaque(false);

        labelresult3.setBackground(new java.awt.Color(255, 255, 102));
        labelresult3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        labelresult3.setForeground(new java.awt.Color(0, 0, 153));

        divSubmit.setText("submit");
        divSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(divSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(labelresult3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divSubmit)
                    .addComponent(labelresult3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel17.setBackground(new java.awt.Color(255, 255, 102));
        jLabel17.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("compute the value of");

        javax.swing.GroupLayout divisionpanelLayout = new javax.swing.GroupLayout(divisionpanel);
        divisionpanel.setLayout(divisionpanelLayout);
        divisionpanelLayout.setHorizontalGroup(
            divisionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(divisionpanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(divisionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtans, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(divisionpanelLayout.createSequentialGroup()
                        .addComponent(nd1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(33, 33, 33)
                        .addComponent(nd2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(divisionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divisionpanelLayout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(95, 95, 95)))
        );
        divisionpanelLayout.setVerticalGroup(
            divisionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisionpanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(divisionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nd2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nd1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(divisionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(divisionpanelLayout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );

        panelComputecard.add(divisionpanel, "card5");

        gamepanel.add(panelComputecard, java.awt.BorderLayout.CENTER);

        panelHome.add(gamepanel, "card2");

        getContentPane().add(panelHome);
        panelHome.setBounds(0, 0, 600, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fastiq/minion.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        labelresult.setText(null);
        tfaans.setText(null);
        TestIQ testIQ = new TestIQ();
        testIQ.rdm();
        na1.setText(Integer.toString(testIQ.no1));
        na2.setText(Integer.toString(testIQ.no2));

        panelComputecard.removeAll();
        panelComputecard.add(additionpanel);
        panelComputecard.repaint();
        panelComputecard.revalidate();
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        panelHome.removeAll();
        panelHome.add(gamepanel);
        panelHome.repaint();
        panelHome.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void subtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtbuttonActionPerformed
        tfsans.setText(null);
        labelresult1.setText(null);
        TestIQ testIQ = new TestIQ();
        testIQ.rdm();
        ns1.setText(Integer.toString(testIQ.no1));
        ns2.setText(Integer.toString(testIQ.no2));
        panelComputecard.removeAll();
        panelComputecard.add(subtractionpanel);
        panelComputecard.repaint();
        panelComputecard.revalidate();
    }//GEN-LAST:event_subtbuttonActionPerformed

    private void multButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multButtonActionPerformed
        mans.setText(null);
        labelresult2.setText(null);
        TestIQ testIQ = new TestIQ();
        testIQ.rdm();
        nm1.setText(Integer.toString(testIQ.no1));
        nm2.setText(Integer.toString(testIQ.no2));
        panelComputecard.removeAll();
        panelComputecard.add(multiplicationpanel);
        panelComputecard.repaint();
        panelComputecard.revalidate();
    }//GEN-LAST:event_multButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        txtans.setText(null);
        labelresult3.setText(null);
        TestIQ testIQ = new TestIQ();
        testIQ.rdm();
        nd1.setText(Integer.toString(testIQ.no1));
        nd2.setText(Integer.toString(testIQ.no2));
        panelComputecard.removeAll();
        panelComputecard.add(divisionpanel);
        panelComputecard.repaint();
        panelComputecard.revalidate();
    }//GEN-LAST:event_divButtonActionPerformed

    private void additionsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionsubmitActionPerformed

        TestIQ testIQ = new TestIQ();
        int val1;
        int val2;
        String text1 = na1.getText();
        val1 = Integer.parseInt(text1);
        String text2 = na2.getText();
        val2 = Integer.parseInt(text2);
        int x = val1 + val2;
        String ye = tfaans.getText();
        int y = Integer.parseInt(ye);
        String ans = Integer.toString(x);
        if (y == x) {
            labelresult.setText("Correct");
            String score = ScoreLabel.getText();
            int level = Integer.parseInt(score);
            int newScore = level + 1;
            ScoreLabel.setText(Integer.toString(newScore));
            testIQ.rdm();
            na1.setText(Integer.toString(testIQ.no1));
            na2.setText(Integer.toString(testIQ.no2));
            tfaans.setText(null);
        } else {
            labelresult.setText("Wrong the ans is" + ans);
            testIQ.rdm();
            na1.setText(Integer.toString(testIQ.no1));
            na2.setText(Integer.toString(testIQ.no2));
            tfaans.setText(null);
        }
    }//GEN-LAST:event_additionsubmitActionPerformed

    private void subdibmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subdibmitActionPerformed

        TestIQ testIQ = new TestIQ();
        int val1;
        int val2;
        String text1 = ns1.getText();
        val1 = Integer.parseInt(text1);
        String text2 = ns2.getText();
        val2 = Integer.parseInt(text2);
        int x = val1 - val2;

        String ye = tfsans.getText();
        int y = Integer.parseInt(ye);
        String ans = Integer.toString(x);
        if (y == x) {
            labelresult1.setText("Correct");
            String score = ScoreLabel.getText();
            int level = Integer.parseInt(score);
            int newScore = level + 1;
            ScoreLabel.setText(Integer.toString(newScore));
            testIQ.rdm();
            ns1.setText(Integer.toString(testIQ.no1));
            ns2.setText(Integer.toString(testIQ.no2));
            tfsans.setText(null);

        } else {
            labelresult1.setText("Wrong the ans is" + " " + ans);
            testIQ.rdm();
            ns1.setText(Integer.toString(testIQ.no1));
            ns2.setText(Integer.toString(testIQ.no2));
            tfsans.setText(null);

        }
    }//GEN-LAST:event_subdibmitActionPerformed

    private void mulsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulsubmitActionPerformed
        TestIQ testIQ = new TestIQ();
        int val1;
        int val2;
        String text1 = nm1.getText();
        val1 = Integer.parseInt(text1);
        String text2 = nm2.getText();
        val2 = Integer.parseInt(text2);
        int x = val1 * val2;

        String ye = mans.getText();
        int y = Integer.parseInt(ye);
        String ans = Integer.toString(x);
        if (y == x) {
            labelresult2.setText("Correct");
            String score = ScoreLabel.getText();
            int level = Integer.parseInt(score);
            int newScore = level + 1;
            ScoreLabel.setText(Integer.toString(newScore));
            testIQ.rdm();
            nm1.setText(Integer.toString(testIQ.no1));
            nm2.setText(Integer.toString(testIQ.no2));
            mans.setText(null);
        } else {
            labelresult2.setText("Wrong the ans is" + ans);
            testIQ.rdm();
            nm1.setText(Integer.toString(testIQ.no1));
            nm2.setText(Integer.toString(testIQ.no2));
            mans.setText(null);
        }
    }//GEN-LAST:event_mulsubmitActionPerformed

    private void p(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p
        // TODO add your handling code here:
    }//GEN-LAST:event_p

    private void divSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divSubmitActionPerformed
        TestIQ testIQ = new TestIQ();
        int val1;
        int val2;
        String text1 = nd1.getText();
        val1 = Integer.parseInt(text1);
        String text2 = nd2.getText();
        val2 = Integer.parseInt(text2);
        int x = val1 / val2;

        String ye = txtans.getText();
        int y = Integer.parseInt(ye);
        String ans = Integer.toString(x);
        if (y == x) {
            labelresult3.setText("Correct");
            String score = ScoreLabel.getText();
            int level = Integer.parseInt(score);
            int newScore = level + 1;
            ScoreLabel.setText(Integer.toString(newScore));
            testIQ.rdm();
            nd1.setText(Integer.toString(testIQ.no1));
            nd2.setText(Integer.toString(testIQ.no2));
            txtans.setText(null);

        } else {
            labelresult3.setText("Wrong the ans is" + ans);
            testIQ.rdm();
            ns1.setText(Integer.toString(testIQ.no1));
            ns2.setText(Integer.toString(testIQ.no2));
            tfsans.setText(null);

        }
    }//GEN-LAST:event_divSubmitActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel additionpanel;
    private javax.swing.JButton additionsubmit;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton divButton;
    private javax.swing.JButton divSubmit;
    private javax.swing.JPanel divisionpanel;
    private javax.swing.JPanel gamepanel;
    private javax.swing.JPanel homepane;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelresult;
    private javax.swing.JLabel labelresult1;
    private javax.swing.JLabel labelresult2;
    private javax.swing.JLabel labelresult3;
    private javax.swing.JTextField mans;
    private javax.swing.JButton mulsubmit;
    private javax.swing.JButton multButton;
    private javax.swing.JPanel multiplicationpanel;
    private javax.swing.JLabel na1;
    private javax.swing.JLabel na2;
    private javax.swing.JLabel nd1;
    private javax.swing.JLabel nd2;
    private javax.swing.JLabel nm1;
    private javax.swing.JLabel nm2;
    private javax.swing.JLabel ns1;
    private javax.swing.JLabel ns2;
    private javax.swing.JPanel panelComputecard;
    private javax.swing.JPanel panelHome;
    private javax.swing.JButton subdibmit;
    private javax.swing.JButton subtbutton;
    private javax.swing.JPanel subtractionpanel;
    private javax.swing.JTextField tfaans;
    private javax.swing.JTextField tfsans;
    private javax.swing.JTextField txtans;
    // End of variables declaration//GEN-END:variables
}
